AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack for Immich Storage Resources (EFS).

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnets where EFS Mount Targets will be created.
  StackNamePrefix:
    Type: String
  ECSServiceSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for ECS services, needed for EFS mount targets.

Resources:
  ImmichEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: !Sub '${StackNamePrefix}-ImmichData'
      # Ensure Backup policy is enabled or configure as needed
      # BackupPolicy:
      #  Status: ENABLED
      LifecyclePolicies: # Example: Move infrequent data to IA
        - TransitionToIA: AFTER_30_DAYS

  # Create Mount Targets in specified private subnets
  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref ImmichEFSFileSystem
      SubnetId: !Select [0, !Ref PrivateSubnetIds]
      SecurityGroups: [!Ref ECSServiceSecurityGroupId]

  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref ImmichEFSFileSystem
      SubnetId: !Select [1, !Ref PrivateSubnetIds]
      SecurityGroups: [!Ref ECSServiceSecurityGroupId]

  PostgresEFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref ImmichEFSFileSystem
      PosixUser:
        # IMPORTANT: Match the UID/GID of the user running postgres in the container
        # The official postgres image often runs as user 'postgres' (uid 999, gid 999)
        # Verify this for the specific image version you use.
        Uid: "999"
        Gid: "999"
      RootDirectory:
        # Creates the '/pgdata' directory on EFS if it doesn't exist
        # Sets ownership to the PosixUser (999:999) and permissions to 700 (only owner can read/write/execute)
        Path: "/pgdata"
        CreationInfo:
          OwnerUid: "999"
          OwnerGid: "999"
          Permissions: "0700" # Only owner access
      AccessPointTags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PostgresAccessPoint"

Outputs:
  EfsFileSystemId:
    Description: ID of the created EFS File System
    Value: !Ref ImmichEFSFileSystem
  PostgresEfsAccessPointId:
    Description: ID of the created Postgres EFS Access Point
    Value !Ref PostgresEFSAccessPoint